spring:
  datasource:
    url: jdbc:mysql://mysql.server:3306/mybatis_spring_boot_sample_integration?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: rootpassword

zeka-stack:
  mybatis:
    enable-sql-explain-interceptor: true
    performmax-time: 2
    sql-format: false
