zeka-stack:
  rest:
    enable-browser: true
    enable-global-parameter-filter: true
    xss:
      enable-xss-filter: true
      exclude-patterns:
        - /json
  logging:
    level:
      root: DEBUG
      project: DEBUG
    file:
      path: /Users/dong4j/Develop/work/fkh-stack/services/fkh-framework/fkh-kernel/fkh-rest-spring-boot/fkh-rest-spring-boot-sample/fkh-rest-spring-boot-sample-servlet/log/

