zeka-stack:
  rest:
    # 默认值, 只有在显式配置为 false 才会禁用组件
    enabled: true
  logging:
    file:
      path: logs
server:
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      dir: undertow
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
  port: 8080

