zeka-stack:
  rest:
    enable-browser: true
    enable-global-parameter-filter: true
    xss:
      enable-xss-filter: true
      exclude-patterns:
        - /json
  logging:
    level:
      root: DEBUG
      project: DEBUG
    file:
      path: ./log/

