spring:
  application:
    name: ${project.artifactId}

zeka-stack:
  app:
    custom:
      config1:
        # 对应配置类中的单个值
        value: 345
        # 对应配置类中的数组
        valueArray: 1,2,3,4,5,6,7,8,9
        # 对应配置类中的 list
        valueList:
          - 13579
          - 246810
        # 对应配置类中的 map
        valueMap:
          name: lili
          age: 20
        # 对应配置类中的 list<map> 或 List<Object>
        valueMapList:
          - name: bob
            age: 21
          - name: caven
            age: 31
        # 对应单独的一个 map
        single-key: singleValue
      config2:
        key: value
      aa: bb
      cc: ${zeka-stack.app.custom.aa}
      name: ${project.artifactId}
    enable-banner: true
