server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://mysql.server:3306?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: rootpassword
