zeka-stack:
  messaging:
    enable: false

spring:
  kafka:
    bootstrap-servers: kafka.server:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


