# 数据源配置, 实现读写分离
spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds1
      # 主数据源
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql.server:3306/ds_0?characterEncoding=utf-8&useSSL=true
        username: root
        password: rootpassword
    # 指定t_order表的数据分布情况, 配置数据节点 m1.t_order_1,m1.t_order_2
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds1.t_order_$->{1..2}
          # 指定t_order表的主键生成策略为 snowflake
          key-generator:
            column: order_id
            type: snowflake
          # 指定t_order表的分片策略, 分片策略包括分片键和分片算法
          table-strategy:
            # 自定义分表策略
            standard:
              precise-algorithm-class-name: OrderShardingAlgorithm
              sharding-column: order_id
    props:
      # 开启SQL显示, 默认false
      sql:
        show: true

